import os
from datetime import datetime
import numpy as np

class EPANETInputGenerator:
    """
    Generate EPANET input files for force main systems
    """
    
    def __init__(self):
        self.title = "Force Main System - EPANET Model"
        self.options = {
            'UNITS': 'SI',
            'HEADLOSS': 'H-W',
            'QUALITY': 'NONE',
            'VISCOSITY': 1.0,
            'DIFFUSIVITY': 1.0,
            'SPECIFIC_GRAVITY': 1.0,
            'TRIALS': 40,
            'ACCURACY': 0.001,
            'UNBALANCED': 'CONTINUE 10',
            'CHECKFREQ': 2,
            'MAXCHECK': 10,
            'DAMPLIMIT': 0
        }
        
    def create_force_main_system(self, config):
        """
        Create EPANET model for force main system
        
        config = {
            'project_title': str,
            'wet_well': {
                'id': str,
                'elevation': float,
                'demand': float (negative for supply)
            },
            'pump': {
                'id': str,
                'from': str,
                'to': str,
                'curve_data': [(flow, head), ...]
            },
            'force_main': {
                'id': str,
                'from': str,
                'to': str,
                'diameter': float (mm),
                'length': float,
                'roughness': float (C value)
            },
            'discharge_node': {
                'id': str,
                'elevation': float,
                'demand': float
            }
        }
        """
        
        content = []
        
        # Title section
        content.append("[TITLE]")
        content.append(f"{config.get('project_title', self.title)}")
        content.append(f"Generated by SWMM Force Main App on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        content.append("Force main system modeled in EPANET for comparison with SWMM5")
        content.append("")
        
        # Junctions section - simplified for realistic pump station
        content.append("[JUNCTIONS]")
        content.append(";ID              Elev        Demand      Pattern         ;")
        
        ww = config['wet_well']
        dn = config['discharge_node']
        pump = config['pump']
        inflow_rate = pump.get('flow', 0.15)  # Same as SWMM5 DWF section
        
        # No junctions needed - wet well is tank, discharge is reservoir
        content.append("")
        
        # Reservoirs section - single discharge reservoir for realistic pump station
        content.append("[RESERVOIRS]")
        content.append(";ID              Head        Pattern         ;")
        
        # Single discharge reservoir at system discharge point
        content.append(f" {'DISCHARGE_RES':<15} {dn['elevation']:<11.2f}                     ;")
        content.append("")
        
        # Tanks section - wet well as tank for realistic pump station
        content.append("[TANKS]")
        content.append(";ID              Elevation   InitLevel   MinLevel    MaxLevel    Diameter    MinVol      VolCurve")
        
        # Wet well tank with realistic dimensions
        tank_diameter = (4 * ww['area'] / 3.14159) ** 0.5  # Calculate diameter from area
        content.append(f" {ww['id']:<15} {ww['invert']:<11.2f} {ww['init_depth']:<11.2f} {0.5:<11.2f} {ww['max_depth']:<11.2f} {tank_diameter:<11.2f} {0:<11.2f}        ;")
        content.append("")
        
        # Pipes section - no pipes needed for pump to reservoir
        content.append("[PIPES]")
        content.append(";ID              Node1           Node2           Length      Diameter    Roughness   MinorLoss   Status")
        content.append("")
        
        # Pumps section - pump directly from tank to reservoir
        content.append("[PUMPS]")
        content.append(";ID              Node1           Node2           Parameters")
        
        curve_id = f"CURVE_{pump['id']}"
        # Pump from wet well tank to discharge reservoir
        content.append(f" {pump['id']:<15} {ww['id']:<15} {'DISCHARGE_RES':<15} HEAD {curve_id}  ;")
        content.append("")
        
        # Valves section (if needed for control)
        content.append("[VALVES]")
        content.append(";ID              Node1           Node2           Diameter    Type    Setting     MinorLoss   ")
        content.append("")
        
        # Tags section
        content.append("[TAGS]")
        content.append("")
        
        # Demands section - tank inflow via external source
        content.append("[DEMANDS]")
        content.append(";Junction        Demand      Pattern         Category")
        # Tank inflow modeled as external source (will be handled in EPANET externally)
        content.append(f"; Tank {ww['id']} receives {inflow_rate*1000:.1f} L/s constant inflow")
        content.append("")
        
        # Status section
        content.append("[STATUS]")
        content.append(";ID              Status/Setting")
        content.append("")
        
        # Patterns section
        content.append("[PATTERNS]")
        content.append(";ID              Multipliers")
        # Add constant pattern
        content.append(" CONSTANT        1.0")
        content.append("")
        
        # Curves section (pump curves)
        content.append("[CURVES]")
        content.append(";ID              X-Value     Y-Value")
        
        # Convert pump curve data (m³/s to L/s, keep head in m)
        for flow_m3s, head_m in pump['curve_data']:
            flow_ls = flow_m3s * 1000  # Convert to L/s
            content.append(f" {curve_id:<15} {flow_ls:<11.3f} {head_m:<11.2f}")
        content.append("")
        
        # Controls section - realistic tank level controls
        content.append("[CONTROLS]")
        content.append("; Control pump based on tank water level")
        content.append(f"LINK {pump['id']} 1.0 IF NODE {ww['id']} ABOVE {pump.get('startup', 2.0)}")
        content.append(f"LINK {pump['id']} 0.0 IF NODE {ww['id']} BELOW {pump.get('shutoff', 0.5)}")
        content.append("")
        
        # Rules section (advanced controls)
        content.append("[RULES]")
        content.append("")
        
        # Energy section
        content.append("[ENERGY]")
        content.append(" Global Efficiency  75.0")
        content.append(" Global Price       0.0")
        content.append(" Demand Charge      0.0")
        content.append("")
        
        # Emitters section
        content.append("[EMITTERS]")
        content.append(";Junction        Coefficient")
        content.append("")
        
        # Quality section
        content.append("[QUALITY]")
        content.append(";Node            InitQual")
        content.append("")
        
        # Sources section - for water quality modeling only
        content.append("[SOURCES]")
        content.append(";Node            Type        Quality     Pattern")
        content.append("")
        
        # Reactions section
        content.append("[REACTIONS]")
        content.append(";Type     Pipe/Tank       Coefficient")
        content.append("")
        
        # Mixing section
        content.append("[MIXING]")
        content.append(";Tank            Model")
        content.append("")
        
        # Times section
        content.append("[TIMES]")
        content.append(" Duration           24:00")
        content.append(" Hydraulic Timestep 1:00")
        content.append(" Quality Timestep   0:05")
        content.append(" Pattern Timestep   1:00")
        content.append(" Pattern Start      0:00")
        content.append(" Report Timestep    1:00")
        content.append(" Report Start       0:00")
        content.append(" Start ClockTime    12 am")
        content.append(" Statistic          NONE")
        content.append("")
        
        # Report section
        content.append("[REPORT]")
        content.append(" Status             No")
        content.append(" Summary            No")
        content.append(" Page               0")
        content.append("")
        
        # Options section
        content.append("[OPTIONS]")
        for key, value in self.options.items():
            content.append(f" {key:<18} {value}")
        content.append("")
        
        # Coordinates section (simplified for tank-to-reservoir system)
        content.append("[COORDINATES]")
        content.append(";Node            X-Coord         Y-Coord")
        content.append(f" {ww['id']:<15} {0:<15.2f} {ww['invert']:<15.2f}")
        content.append(f" {'DISCHARGE_RES':<15} {1000:<15.2f} {dn['elevation']:<15.2f}")
        content.append("")
        
        # Vertices section
        content.append("[VERTICES]")
        content.append(";Link            X-Coord         Y-Coord")
        content.append("")
        
        # Labels section
        content.append("[LABELS]")
        content.append(";X-Coord           Y-Coord          Label & Anchor Node")
        content.append("")
        
        # Backdrop section
        content.append("[BACKDROP]")
        content.append(" DIMENSIONS     0.00    0.00    10000.00    10000.00")
        content.append(" UNITS          None")
        content.append(" FILE           ")
        content.append(" OFFSET         0.00    0.00")
        content.append("")
        
        content.append("[END]")
        
        return "\n".join(content)
    
    def create_network_system(self, nodes, links, pumps):
        """
        Create EPANET model for complex force main network
        
        Parameters:
        nodes: Dictionary of node configurations
        links: Dictionary of link configurations  
        pumps: Dictionary of pump configurations
        """
        content = []
        
        # Header
        content.append("[TITLE]")
        content.append("Force Main Network - EPANET Model")
        content.append(f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        content.append("")
        
        # Process nodes
        junctions = []
        reservoirs = []
        tanks = []
        
        for node_id, node in nodes.items():
            if node['type'] == 'junction':
                junctions.append((node_id, node))
            elif node['type'] == 'wet_well':
                tanks.append((node_id, node))  # Model as tank
            elif node['type'] == 'outfall':
                reservoirs.append((node_id, node))
        
        # Junctions section
        content.append("[JUNCTIONS]")
        content.append(";ID              Elev        Demand      Pattern         ;")
        
        for node_id, node in junctions:
            elevation = node.get('elevation', node.get('invert', 100.0))
            demand = node.get('demand', 0.0) * 1000  # Convert to L/s
            content.append(f" {node_id:<15} {elevation:<11.2f} {demand:<11.3f}                     ;")
        content.append("")
        
        # Reservoirs section
        content.append("[RESERVOIRS]")
        content.append(";ID              Head        Pattern         ;")
        
        for node_id, node in reservoirs:
            head = node.get('stage', node.get('invert', 100.0))
            content.append(f" {node_id:<15} {head:<11.2f}                     ;")
        content.append("")
        
        # Tanks section
        content.append("[TANKS]")
        content.append(";ID              Elevation   InitLevel   MinLevel    MaxLevel    Diameter    MinVol      VolCurve")
        
        for node_id, node in tanks:
            elevation = node.get('invert', 100.0)
            init_level = node.get('init_depth', 1.0)
            min_level = 0.1
            max_level = node.get('max_depth', 3.0)
            area = node.get('area', 50.0)
            diameter = np.sqrt(4 * area / np.pi)
            
            content.append(f" {node_id:<15} {elevation:<11.2f} {init_level:<11.2f} {min_level:<11.2f} {max_level:<11.2f} {diameter:<11.2f} {0:<11.2f}        ;")
        content.append("")
        
        # Pipes section
        content.append("[PIPES]")
        content.append(";ID              Node1           Node2           Length      Diameter    Roughness   MinorLoss   Status")
        
        for link_id, link in links.items():
            if link['type'] == 'force_main':
                length = link['length']
                diameter_mm = link['diameter'] * 1000  # Convert to mm
                roughness = link.get('roughness', 120)  # Default C value
                
                content.append(f" {link_id:<15} {link['from']:<15} {link['to']:<15} {length:<11.2f} {diameter_mm:<11.1f} {roughness:<11.3f} {0:<11.3f} Open  ;")
        content.append("")
        
        # Pumps section
        content.append("[PUMPS]")
        content.append(";ID              Node1           Node2           Parameters")
        
        for pump_id, pump in pumps.items():
            curve_id = f"CURVE_{pump_id}"
            content.append(f" {pump_id:<15} {pump['from']:<15} {pump['to']:<15} HEAD {curve_id}  ;")
        content.append("")
        
        # Pump curves
        content.append("[CURVES]")
        content.append(";ID              X-Value     Y-Value")
        
        for pump_id, pump in pumps.items():
            curve_id = f"CURVE_{pump_id}"
            if 'curve_data' in pump:
                for flow_m3s, head_m in pump['curve_data']:
                    flow_ls = flow_m3s * 1000  # Convert to L/s
                    content.append(f" {curve_id:<15} {flow_ls:<11.3f} {head_m:<11.2f}")
        content.append("")
        
        # Standard sections
        content.extend([
            "[DEMANDS]", "", 
            "[STATUS]", "",
            "[PATTERNS]", " CONSTANT        1.0", "",
            "[CONTROLS]", "",
            "[RULES]", "",
            "[ENERGY]", " Global Efficiency  75.0", "",
            "[EMITTERS]", "",
            "[QUALITY]", "",
            "[SOURCES]", "",
            "[REACTIONS]", "",
            "[MIXING]", "",
            "[TIMES]",
            " Duration           24:00",
            " Hydraulic Timestep 1:00",
            " Report Timestep    1:00",
            "",
            "[REPORT]",
            " Status             No",
            "",
            "[OPTIONS]"
        ])
        
        for key, value in self.options.items():
            content.append(f" {key:<18} {value}")
        
        content.extend(["", "[COORDINATES]", "", "[END]"])
        
        return "\n".join(content)
    
    def validate_epanet_input(self, inp_content):
        """
        Validate EPANET input file for common errors
        
        Returns:
        dict: Validation results
        """
        lines = inp_content.split('\n')
        errors = []
        warnings = []
        
        # Check for required sections
        required_sections = ['[TITLE]', '[JUNCTIONS]', '[PIPES]', '[OPTIONS]', '[END]']
        found_sections = []
        
        for line in lines:
            line = line.strip()
            if line.startswith('[') and line.endswith(']'):
                found_sections.append(line)
        
        for section in required_sections:
            if section not in found_sections:
                errors.append(f"Missing required section: {section}")
        
        # Check for pumps without curves
        if '[PUMPS]' in found_sections and '[CURVES]' not in found_sections:
            warnings.append("Pumps defined but no pump curves provided")
        
        # Check for proper file ending
        if not inp_content.strip().endswith('[END]'):
            warnings.append("File should end with [END] section")
        
        return {
            'errors': errors,
            'warnings': warnings,
            'is_valid': len(errors) == 0,
            'sections_found': found_sections
        }