import os
from datetime import datetime
import numpy as np

class SWMMInputGenerator:
    """
    Generate SWMM5 input files for force main systems
    
    MODELING RULES FOR SWMM5-EPANET CONSISTENCY:
    - Use FORCE_MAIN link type (not CONDUIT) with proper XSECTIONS
    - Physical parameters (diameter, length, roughness) must match EPANET
    - Use DYNWAVE routing for accurate pressure simulation (Rule 7)
    - Friction equation (H-W or D-W) must match EPANET settings
    - Wet well modeled as STORAGE node for realistic pump station
    - Pump curves must be identical to EPANET pump curves
    - Minor losses included in XSECTIONS configuration
    - Results should match EPANET within 5-10% tolerance
    """
    
    def __init__(self):
        self.title = "Force Main System"
        self.options = {
            'FLOW_UNITS': 'CMS',
            'INFILTRATION': 'HORTON',
            'FLOW_ROUTING': 'DYNWAVE',
            'FORCE_MAIN_EQUATION': 'H-W',
            'SURCHARGE_METHOD': 'SLOT',
            'VARIABLE_STEP': 0.75,
            'LENGTHENING_STEP': 0,
            'MIN_SURFAREA': 1.14,
            'NORMAL_FLOW_LIMITED': 'BOTH',
            'SKIP_STEADY_STATE': 'NO',
            'IGNORE_RAINFALL': 'NO',
            'IGNORE_SNOWMELT': 'NO',
            'IGNORE_GROUNDWATER': 'NO',
            'IGNORE_ROUTING': 'NO',
            'IGNORE_QUALITY': 'NO'
        }
        
        # Default time settings
        self.start_date = "01/01/2024"
        self.start_time = "00:00:00"
        self.end_date = "01/02/2024"
        self.end_time = "00:00:00"
        self.dry_days = 0
        self.report_step = "00:15:00"
        self.wet_step = "00:05:00"
        self.dry_step = "01:00:00"
        self.routing_step = "0:00:30"
        
    def create_header_sections(self, project_title):
        """Create header sections of SWMM input file"""
        content = []
        
        # Title section
        content.append("[TITLE]")
        content.append(f";;{project_title}")
        content.append(f";;Generated by SWMM Force Main App on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        content.append("")
        
        # Options section (includes all time parameters)
        content.append("[OPTIONS]")
        for key, value in self.options.items():
            content.append(f"{key:<25} {value}")
        
        # Add time parameters to OPTIONS section
        content.append(f"{'START_DATE':<25} {self.start_date}")
        content.append(f"{'START_TIME':<25} {self.start_time}")
        content.append(f"{'REPORT_START_DATE':<25} {self.start_date}")
        content.append(f"{'REPORT_START_TIME':<25} {self.start_time}")
        content.append(f"{'END_DATE':<25} {self.end_date}")
        content.append(f"{'END_TIME':<25} {self.end_time}")
        content.append(f"{'SWEEP_START':<25} 01/01")
        content.append(f"{'SWEEP_END':<25} 12/31")
        content.append(f"{'DRY_DAYS':<25} {self.dry_days}")
        content.append(f"{'REPORT_STEP':<25} {self.report_step}")
        content.append(f"{'WET_STEP':<25} {self.wet_step}")
        content.append(f"{'DRY_STEP':<25} {self.dry_step}")
        content.append(f"{'ROUTING_STEP':<25} {self.routing_step}")
        content.append("")
        
        # Evaporation section
        content.append("[EVAPORATION]")
        content.append(";;Data Source    Parameters")
        content.append(";;-------------- ----------------")
        content.append("CONSTANT         0.0")
        content.append("DRY_ONLY         NO")
        content.append("")
        
        # No raingages or timeseries needed for constant inflow
        
        return content
    
    def create_report_section(self):
        """Create report section only - time parameters are now in OPTIONS"""
        content = []
        
        content.append("[REPORT]")
        content.append(";;Reporting Options")
        content.append("INPUT      NO")
        content.append("CONTROLS   NO")
        content.append("SUBCATCHMENTS NONE")  
        content.append("NODES ALL")
        content.append("LINKS ALL")
        content.append("")
        
        return content
    
    def create_coordinates_section(self, config, system_type='force_main'):
        """Create coordinates section for network visualization"""
        content = []
        
        content.append("[COORDINATES]")
        content.append(";;Node           X-Coord            Y-Coord           ")
        content.append(";;-------------- ------------------ ------------------")
        
        if system_type == 'force_main':
            # Create linear layout for force main system
            ww = config['wet_well']
            fm = config['force_main'] 
            dn = config['discharge_node']
            pump_discharge_node = fm['from']
            
            # Wet well at origin
            content.append(f"{ww['id']:<16} {0.0:<18.2f} {0.0:<18.2f}")
            
            # Pump discharge node slightly offset
            content.append(f"{pump_discharge_node:<16} {100.0:<18.2f} {0.0:<18.2f}")
            
            # Discharge node along the force main
            force_main_length = fm.get('length', 1000)
            x_discharge = 100.0 + force_main_length * 0.8
            content.append(f"{dn['id']:<16} {x_discharge:<18.2f} {0.0:<18.2f}")
            
            # Outfall at the end
            x_outfall = x_discharge + 100.0
            content.append(f"{'OUTFALL1':<16} {x_outfall:<18.2f} {0.0:<18.2f}")
            
        elif system_type == 'network':
            # For network systems, use provided coordinates or generate them
            nodes = config.get('nodes', {})
            x_offset = 0
            y_offset = 0
            
            for node_id, node in nodes.items():
                x_coord = node.get('x_coord', x_offset)
                y_coord = node.get('y_coord', y_offset)
                content.append(f"{node_id:<16} {x_coord:<18.2f} {y_coord:<18.2f}")
                
                # Auto-increment if no coordinates provided
                if 'x_coord' not in node:
                    x_offset += 200
                    
        content.append("")
        return content
    
    def create_polygons_section(self, config):
        """Create polygons section for subcatchment visualization"""
        content = []
        
        content.append("[POLYGONS]")
        content.append(";;Subcatchment   X-Coord            Y-Coord           ")
        content.append(";;-------------- ------------------ ------------------")
        
        # Create simple rectangular polygon for subcatchment SUB1
        # This creates a small catchment area near the wet well
        content.append(f"{'SUB1':<16} {-50.0:<18.2f} {-50.0:<18.2f}")
        content.append(f"{'SUB1':<16} {50.0:<18.2f} {-50.0:<18.2f}")
        content.append(f"{'SUB1':<16} {50.0:<18.2f} {50.0:<18.2f}")
        content.append(f"{'SUB1':<16} {-50.0:<18.2f} {50.0:<18.2f}")
        content.append("")
        
        return content
    
    def create_force_main_system(self, config):
        """
        Create complete force main system
        
        config = {
            'project_title': str,
            'flow_units': str,
            'wet_well': {
                'id': str,
                'invert': float,
                'max_depth': float,
                'init_depth': float,
                'area': float
            },
            'pump': {
                'id': str,
                'from': str,
                'to': str,
                'curve': str,
                'startup': float,
                'shutoff': float,
                'curve_data': [(flow, head), ...]
            },
            'force_main': {
                'id': str,
                'from': str,
                'to': str,
                'diameter': float,
                'length': float,
                'roughness': float
            },
            'discharge_node': {
                'id': str,
                'elevation': float,
                'max_depth': float,
                'surcharge_depth': float
            }
        }
        """
        
        # Update options based on config
        if 'flow_units' in config:
            self.options['FLOW_UNITS'] = config['flow_units']
        
        content = []
        
        # Header sections
        content.extend(self.create_header_sections(config.get('project_title', self.title)))
        
        # Extract commonly used variables
        ww = config['wet_well']
        pump = config.get('pump', {})
        
        # Junctions section
        content.append("[JUNCTIONS]")
        content.append(";;Name           Elevation  MaxDepth   InitDepth  SurDepth   Aponded   ")
        content.append(";;-------------- ---------- ---------- ---------- ---------- ----------")
        
        # Add intermediate node for pump discharge
        pump_discharge_node = config['force_main']['from']
        content.append(f"{pump_discharge_node:<16} {ww['invert'] + 1.0:<10.2f} {2.0:<10.2f} {0.0:<10.2f} {100.0:<10.2f} {0.0:<10.2f}")
        
        # Add discharge node with surcharge capability
        dn = config['discharge_node']
        # Ensure surcharge depth is at least 100 for force main nodes
        surcharge_depth = max(dn.get('surcharge_depth', 100.0), 100.0)
        content.append(f"{dn['id']:<16} {dn['elevation']:<10.2f} {dn['max_depth']:<10.2f} {0.0:<10.2f} {surcharge_depth:<10.2f} {0.0:<10.2f}")
        content.append("")
        
        # Outfalls section
        content.append("[OUTFALLS]")
        content.append(";;Name           Elevation  Type       Stage Data       Gated    Route To        ")
        content.append(";;-------------- ---------- ---------- ---------------- -------- ----------------")
        # Set outfall elevation lower than discharge node for gravity flow downhill
        outfall_elevation = dn['elevation'] - 2.0  # 2 meters below discharge node for adequate slope
        content.append(f"{'OUTFALL1':<16} {outfall_elevation:<10.2f} {'FREE':<10} {'':<16} {'NO':<8} {'':<16}")
        content.append("")
        
        # Storage section for wet well tank - realistic pump station design
        content.append("[STORAGE]")
        content.append(";;Name           Elev.    MaxDepth   InitDepth  Shape      Curve Name/Params            N/A      Fevap    Psi      Ksat     IMD     ")
        content.append(";;-------------- -------- ---------- ----------- ---------- ---------------------------- -------- -------- -------- -------- --------")
        content.append(f"{ww['id']:<16} {ww['invert']:<8.2f} {ww['max_depth']:<10.2f} {ww['init_depth']:<10.2f} {'FUNCTIONAL':<10} {ww['area']:<8.2f} 0 0 0 {0.0:<8.2f} {0.0:<8.2f} {0.0:<8.2f} {0.0:<8.2f}")
        content.append("")
        
        # Conduits section
        content.append("[CONDUITS]")
        content.append(";;Name           From Node        To Node          Length     Roughness  InOffset   OutOffset  InitFlow   MaxFlow   ")
        content.append(";;-------------- ---------------- ---------------- ---------- ---------- ---------- ---------- ---------- ----------")
        
        fm = config['force_main']
        content.append(f"{fm['id']:<16} {fm['from']:<16} {fm['to']:<16} {fm['length']:<10.2f} {fm['roughness']:<10.4f} {0.0:<10.2f} {0.0:<10.2f} {0.0:<10.2f} {0.0:<10.2f}")
        
        # Add gravity conduit from discharge node to outfall
        content.append(f"{'GRAVITY1':<16} {dn['id']:<16} {'OUTFALL1':<16} {100.0:<10.2f} {0.013:<10.4f} {0.0:<10.2f} {0.0:<10.2f} {0.0:<10.2f} {0.0:<10.2f}")
        content.append("")
        
        # Pumps section
        content.append("[PUMPS]")
        content.append(";;Name           From Node        To Node          Pump Curve       Status   Sartup Shutoff ")
        content.append(";;-------------- ---------------- ---------------- ---------------- ------ -------- --------")
        
        pump = config['pump']
        content.append(f"{pump['id']:<16} {pump['from']:<16} {pump['to']:<16} {pump['curve']:<16} {'ON':<6} {pump['startup']:<8.2f} {pump['shutoff']:<8.2f}")
        content.append("")
        
        # XSections section
        content.append("[XSECTIONS]")
        content.append(";;Link           Shape        Geom1            Geom2      Geom3      Geom4      Barrels    Culvert   ")
        content.append(";;-------------- ------------ ---------------- ---------- ---------- ---------- ---------- ----------")
        
        # Force main cross-section
        # Geom2 for FORCE_MAIN should be HW C coefficient (not Manning's n)
        hw_c = 120 if fm['roughness'] < 1 else fm['roughness']  # Convert Manning's n to HW C if needed
        content.append(f"{fm['id']:<16} {'FORCE_MAIN':<12} {fm['diameter']:<16.3f} {hw_c:<10.3f} {0:<10.3f} {0:<10.3f} {1:<10} {0:<10}")
        
        # Gravity conduit cross-section
        gravity_diameter = max(0.2, fm['diameter'] * 1.5)  # Size appropriately
        content.append(f"{'GRAVITY1':<16} {'CIRCULAR':<12} {gravity_diameter:<16.3f} {0:<10.3f} {0:<10.3f} {0:<10.3f} {1:<10} {0:<10}")
        content.append("")
        
        # Curves section
        content.append("[CURVES]")
        content.append(";;Name           Type       X-Value    Y-Value   ")
        content.append(";;-------------- ---------- ---------- ----------")
        
        # First line has curve name and pump type
        if pump['curve_data']:
            flow, head = pump['curve_data'][0]
            content.append(f"{pump['curve']:<16} {'Pump3':<10} {flow:<10.4f} {head:<10.2f}")
            
            # Subsequent lines have only curve name and values
            for flow, head in pump['curve_data'][1:]:
                content.append(f"{pump['curve']:<16} {'':<10} {flow:<10.4f} {head:<10.2f}")
        content.append("")
        
        # Controls section for pump operation
        content.append("[CONTROLS]")
        content.append(f"RULE R1")
        content.append(f"IF NODE {ww['id']} DEPTH > {pump['startup']}")
        content.append(f"THEN PUMP {pump['id']} STATUS = ON")
        content.append("")
        content.append(f"RULE R2")
        content.append(f"IF NODE {ww['id']} DEPTH < {pump['shutoff']}")
        content.append(f"THEN PUMP {pump['id']} STATUS = OFF")
        content.append("")
        
        # Coordinates section for network visualization
        content.extend(self.create_coordinates_section(config, 'force_main'))
        
        # No polygons section needed without subcatchments
        
        # Report section
        content.extend(self.create_report_section())
        
        # Files section removed to avoid hotstart file errors
        
        # DWF (Dry Weather Flow) for constant inflow to wet well - at end of file
        content.append("[DWF]")
        content.append(";;Node           Constituent      Baseline   Pattern   ")
        content.append(";;-------------- ---------------- ---------- ----------")
        ww = config['wet_well']
        # Use pump flow rate as the constant inflow (or default value)
        pump = config.get('pump', {})
        inflow_rate = pump.get('flow', 0.15)  # Default 0.15 m³/s if not specified
        content.append(f"{ww['id']:<16} {'FLOW':<16} {inflow_rate:<10.6f} {'':<10}")
        content.append("")
        
        return "\n".join(content)
    
    def create_multiple_pump_system(self, config):
        """
        Create system with multiple pumps in parallel
        
        config = {
            'project_title': str,
            'wet_well': {...},
            'pumps': [
                {'id': str, 'curve': str, 'startup': float, 'shutoff': float, 'curve_data': [...]},
                ...
            ],
            'force_mains': [
                {'id': str, 'diameter': float, 'length': float, 'roughness': float},
                ...
            ],
            'discharge_node': {...}
        }
        """
        # Implementation for multiple pump systems
        # This would extend the single pump system to handle multiple pumps
        pass
    
    def create_network_system(self, nodes, links, pumps):
        """
        Create complex network system from node/link data
        
        Parameters:
        nodes: Dictionary of node configurations
        links: Dictionary of link configurations  
        pumps: Dictionary of pump configurations
        """
        content = []
        
        # Header
        content.extend(self.create_header_sections("Force Main Network"))
        
        # Process nodes
        junctions = []
        storage_nodes = []
        outfalls = []
        
        for node_id, node in nodes.items():
            if node['type'] == 'junction':
                junctions.append(node_id)
            elif node['type'] == 'wet_well':
                storage_nodes.append(node_id)
            elif node['type'] == 'outfall':
                outfalls.append(node_id)
        
        # Junctions section
        if junctions:
            content.append("[JUNCTIONS]")
            content.append(";;Name           Elevation  MaxDepth   InitDepth  SurDepth   Aponded   ")
            content.append(";;-------------- ---------- ---------- ---------- ---------- ----------")
            
            for node_id in junctions:
                node = nodes[node_id]
                # Ensure surcharge depth is at least 100 for force main nodes
                surcharge_depth = max(node.get('surcharge_depth', 100.0), 100.0)
                content.append(f"{node_id:<16} {node['invert']:<10.2f} {node.get('max_depth', 2.0):<10.2f} {0.0:<10.2f} {surcharge_depth:<10.2f} {0.0:<10.2f}")
            content.append("")
        
        # Storage section
        if storage_nodes:
            content.append("[STORAGE]")
            content.append(";;Name           Elev.    MaxDepth   InitDepth  Shape      Curve Name/Params            N/A      Fevap    Psi      Ksat     IMD     ")
            content.append(";;-------------- -------- ---------- ----------- ---------- ---------------------------- -------- -------- -------- -------- --------")
            
            for node_id in storage_nodes:
                node = nodes[node_id]
                content.append(f"{node_id:<16} {node['invert']:<8.2f} {node['max_depth']:<10.2f} {node.get('init_depth', 1.0):<10.2f} {'FUNCTIONAL':<10} {node.get('area', 50.0):<8.2f} 0 0 0 {0.0:<8.2f} {0.0:<8.2f} {0.0:<8.2f} {0.0:<8.2f}")
            content.append("")
        
        # Outfalls section
        if outfalls:
            content.append("[OUTFALLS]")
            content.append(";;Name           Elevation  Type       Stage Data       Gated    Route To        ")
            content.append(";;-------------- ---------- ---------- ---------------- -------- ----------------")
            
            for node_id in outfalls:
                node = nodes[node_id]
                content.append(f"{node_id:<16} {node['invert']:<10.2f} {'FREE':<10} {'':<16} {'NO':<8} {'':<16}")
            content.append("")
        
        # Conduits section
        content.append("[CONDUITS]")
        content.append(";;Name           From Node        To Node          Length     Roughness  InOffset   OutOffset  InitFlow   MaxFlow   ")
        content.append(";;-------------- ---------------- ---------------- ---------- ---------- ---------- ---------- ---------- ----------")
        
        for link_id, link in links.items():
            if link['type'] == 'force_main':
                content.append(f"{link_id:<16} {link['from']:<16} {link['to']:<16} {link['length']:<10.2f} {link['roughness']:<10.4f} {0.0:<10.2f} {0.0:<10.2f} {0.0:<10.2f} {0.0:<10.2f}")
        content.append("")
        
        # Pumps section
        if pumps:
            content.append("[PUMPS]")
            content.append(";;Name           From Node        To Node          Pump Curve       Status   Sartup Shutoff ")
            content.append(";;-------------- ---------------- ---------------- ---------------- ------ -------- --------")
            
            for pump_id, pump in pumps.items():
                content.append(f"{pump_id:<16} {pump['from']:<16} {pump['to']:<16} {pump['curve']:<16} {'ON':<6} {pump.get('startup', 2.0):<8.2f} {pump.get('shutoff', 0.5):<8.2f}")
            content.append("")
        
        # Cross-sections
        content.append("[XSECTIONS]")
        content.append(";;Link           Shape        Geom1            Geom2      Geom3      Geom4      Barrels    Culvert   ")
        content.append(";;-------------- ------------ ---------------- ---------- ---------- ---------- ---------- ----------")
        
        for link_id, link in links.items():
            if link['type'] == 'force_main':
                # Geom2 for FORCE_MAIN should be HW C coefficient (not Manning's n)
                hw_c = 120 if link['roughness'] < 1 else link['roughness']  # Convert Manning's n to HW C if needed
                content.append(f"{link_id:<16} {'FORCE_MAIN':<12} {link['diameter']:<16.3f} {hw_c:<10.3f} {0:<10.3f} {0:<10.3f} {1:<10} {0:<10}")
        content.append("")
        
        # Pump curves
        if pumps:
            content.append("[CURVES]")
            content.append(";;Name           Type       X-Value    Y-Value   ")
            content.append(";;-------------- ---------- ---------- ----------")
            
            for pump_id, pump in pumps.items():
                if 'curve_data' in pump and pump['curve_data']:
                    # First line has curve name and pump type
                    flow, head = pump['curve_data'][0]
                    content.append(f"{pump['curve']:<16} {'Pump3':<10} {flow:<10.4f} {head:<10.2f}")
                    
                    # Subsequent lines have only curve name and values
                    for flow, head in pump['curve_data'][1:]:
                        content.append(f"{pump['curve']:<16} {'':<10} {flow:<10.4f} {head:<10.2f}")
            content.append("")
        
        # Coordinates section for network visualization
        content.extend(self.create_coordinates_section({'nodes': nodes}, 'network'))
        
        # Report section
        content.extend(self.create_report_section())
        
        return "\n".join(content)
    
    def validate_input_file(self, inp_content):
        """
        Validate SWMM input file for common errors
        
        Returns:
        dict: Validation results
        """
        lines = inp_content.split('\n')
        errors = []
        warnings = []
        
        # Check for required sections
        required_sections = ['[TITLE]', '[OPTIONS]']
        found_sections = []
        
        for line in lines:
            line = line.strip()
            if line.startswith('[') and line.endswith(']'):
                found_sections.append(line)
        
        for section in required_sections:
            if section not in found_sections:
                errors.append(f"Missing required section: {section}")
        
        # Check for nodes and links
        has_nodes = any('[JUNCTIONS]' in s or '[STORAGE]' in s or '[OUTFALLS]' in s for s in found_sections)
        has_links = any('[CONDUITS]' in s or '[PUMPS]' in s for s in found_sections)
        
        if not has_nodes:
            errors.append("No nodes defined in model")
        if not has_links:
            warnings.append("No links defined in model")
        
        # Check for cross-sections if conduits exist
        if '[CONDUITS]' in found_sections and '[XSECTIONS]' not in found_sections:
            errors.append("Conduits defined but no cross-sections provided")
        
        return {
            'errors': errors,
            'warnings': warnings,
            'is_valid': len(errors) == 0,
            'sections_found': found_sections
        }
