import os
from datetime import datetime
import numpy as np

class SWMMInputGenerator:
    """
    Generate SWMM5 input files for force main systems
    """
    
    def __init__(self):
        self.title = "Force Main System"
        self.options = {
            'FLOW_UNITS': 'CMS',
            'INFILTRATION': 'HORTON',
            'FLOW_ROUTING': 'DYNWAVE',
            'FORCE_MAIN_EQUATION': 'H-W',
            'SURCHARGE_METHOD': 'SLOT',
            'VARIABLE_STEP': 0.75,
            'LENGTHENING_STEP': 0,
            'MIN_SURFAREA': 1.14,
            'NORMAL_FLOW_LIMITED': 'BOTH',
            'SKIP_STEADY_STATE': 'NO',
            'IGNORE_RAINFALL': 'NO',
            'IGNORE_SNOWMELT': 'NO',
            'IGNORE_GROUNDWATER': 'NO',
            'IGNORE_ROUTING': 'NO',
            'IGNORE_QUALITY': 'NO'
        }
        
        # Default time settings
        self.start_date = "01/01/2024"
        self.start_time = "00:00:00"
        self.end_date = "01/02/2024"
        self.end_time = "00:00:00"
        self.dry_days = 0
        self.report_step = "00:15:00"
        self.wet_step = "00:05:00"
        self.dry_step = "01:00:00"
        self.routing_step = "0:00:30"
        
    def create_header_sections(self, project_title):
        """Create header sections of SWMM input file"""
        content = []
        
        # Title section
        content.append("[TITLE]")
        content.append(f";;{project_title}")
        content.append(f";;Generated by SWMM Force Main App on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        content.append("")
        
        # Options section (includes all time parameters)
        content.append("[OPTIONS]")
        for key, value in self.options.items():
            content.append(f"{key:<25} {value}")
        
        # Add time parameters to OPTIONS section
        content.append(f"{'START_DATE':<25} {self.start_date}")
        content.append(f"{'START_TIME':<25} {self.start_time}")
        content.append(f"{'REPORT_START_DATE':<25} {self.start_date}")
        content.append(f"{'REPORT_START_TIME':<25} {self.start_time}")
        content.append(f"{'END_DATE':<25} {self.end_date}")
        content.append(f"{'END_TIME':<25} {self.end_time}")
        content.append(f"{'SWEEP_START':<25} 01/01")
        content.append(f"{'SWEEP_END':<25} 12/31")
        content.append(f"{'DRY_DAYS':<25} {self.dry_days}")
        content.append(f"{'REPORT_STEP':<25} {self.report_step}")
        content.append(f"{'WET_STEP':<25} {self.wet_step}")
        content.append(f"{'DRY_STEP':<25} {self.dry_step}")
        content.append(f"{'ROUTING_STEP':<25} {self.routing_step}")
        content.append("")
        
        # Evaporation section
        content.append("[EVAPORATION]")
        content.append(";;Data Source    Parameters")
        content.append(";;-------------- ----------------")
        content.append("CONSTANT         0.0")
        content.append("DRY_ONLY         NO")
        content.append("")
        
        # Raingages section (minimal)
        content.append("[RAINGAGES]")
        content.append(";;Name           Format    Interval SCF      Source    ")
        content.append(";;-------------- --------- ------ ------ ------------")
        content.append("RG1              INTENSITY 1:00     1.0    TIMESERIES TS1")
        content.append("")
        
        # Time series (minimal)
        content.append("[TIMESERIES]")
        content.append(";;Name           Date       Time       Value     ")
        content.append(";;-------------- ---------- ---------- ----------")
        content.append("TS1              1/1/2024   0:00       0.0")
        content.append("TS1              1/2/2024   0:00       0.0")
        content.append("")
        
        return content
    
    def create_report_section(self):
        """Create report section only - time parameters are now in OPTIONS"""
        content = []
        
        content.append("[REPORT]")
        content.append(";;Reporting Options")
        content.append("INPUT      NO")
        content.append("CONTROLS   NO")
        content.append("SUBCATCHMENTS ALL")  
        content.append("NODES ALL")
        content.append("LINKS ALL")
        content.append("")
        
        return content
    
    def create_force_main_system(self, config):
        """
        Create complete force main system
        
        config = {
            'project_title': str,
            'flow_units': str,
            'wet_well': {
                'id': str,
                'invert': float,
                'max_depth': float,
                'init_depth': float,
                'area': float
            },
            'pump': {
                'id': str,
                'from': str,
                'to': str,
                'curve': str,
                'startup': float,
                'shutoff': float,
                'curve_data': [(flow, head), ...]
            },
            'force_main': {
                'id': str,
                'from': str,
                'to': str,
                'diameter': float,
                'length': float,
                'roughness': float
            },
            'discharge_node': {
                'id': str,
                'elevation': float,
                'max_depth': float,
                'surcharge_depth': float
            }
        }
        """
        
        # Update options based on config
        if 'flow_units' in config:
            self.options['FLOW_UNITS'] = config['flow_units']
        
        content = []
        
        # Header sections
        content.extend(self.create_header_sections(config.get('project_title', self.title)))
        
        # Subcatchments (minimal for wet well inflow)
        content.append("[SUBCATCHMENTS]")
        content.append(";;Name           Rain Gage        Outlet           Area     %Imperv  Width    %Slope   CurbLen  SnowPack        ")
        content.append(";;-------------- ---------------- ---------------- -------- -------- -------- -------- -------- ----------------")
        ww = config['wet_well']
        content.append(f"{'SUB1':<16} {'RG1':<16} {ww['id']:<16} {1.0:<8.2f} {100.0:<8.1f} {100.0:<8.1f} {0.5:<8.1f} {0:<8.1f}")
        content.append("")
        
        # Subareas
        content.append("[SUBAREAS]")
        content.append(";;Subcatchment   N-Imperv   N-Perv     S-Imperv   S-Perv     PctZero    RouteTo    PctRouted ")
        content.append(";;-------------- ---------- ---------- ---------- ---------- ---------- ---------- ----------")
        content.append(f"{'SUB1':<16} {0.01:<10.2f} {0.1:<10.2f} {0.05:<10.2f} {0.05:<10.2f} {25.0:<10.1f} {'OUTLET':<10} {100.0:<10.1f}")
        content.append("")
        
        # Infiltration
        content.append("[INFILTRATION]")
        content.append(";;Subcatchment   MaxRate    MinRate    Decay      DryTime    MaxInfil  ")
        content.append(";;-------------- ---------- ---------- ---------- ---------- ----------")
        content.append(f"{'SUB1':<16} {3.0:<10.1f} {0.5:<10.1f} {4.0:<10.1f} {7.0:<10.1f} {0.0:<10.1f}")
        content.append("")
        
        # Junctions section
        content.append("[JUNCTIONS]")
        content.append(";;Name           Elevation  MaxDepth   InitDepth  SurDepth   Aponded   ")
        content.append(";;-------------- ---------- ---------- ---------- ---------- ----------")
        
        # Add intermediate node for pump discharge
        pump_discharge_node = config['force_main']['from']
        content.append(f"{pump_discharge_node:<16} {ww['invert'] + 1.0:<10.2f} {2.0:<10.2f} {0.0:<10.2f} {0.0:<10.2f} {0.0:<10.2f}")
        
        # Add discharge node with surcharge capability
        dn = config['discharge_node']
        content.append(f"{dn['id']:<16} {dn['elevation']:<10.2f} {dn['max_depth']:<10.2f} {0.0:<10.2f} {dn['surcharge_depth']:<10.2f} {0.0:<10.2f}")
        content.append("")
        
        # Outfalls section
        content.append("[OUTFALLS]")
        content.append(";;Name           Elevation  Type       Stage Data       Gated    Route To        ")
        content.append(";;-------------- ---------- ---------- ---------------- -------- ----------------")
        outfall_elevation = dn['elevation'] + dn['max_depth'] + dn['surcharge_depth']
        content.append(f"{'OUTFALL1':<16} {outfall_elevation:<10.2f} {'FREE':<10} {'':<16} {'NO':<8} {'':<16}")
        content.append("")
        
        # Storage section for wet well
        content.append("[STORAGE]")
        content.append(";;Name           Elev.    MaxDepth   InitDepth  Shape      Curve Name/Params            N/A      Fevap    Psi      Ksat     IMD     ")
        content.append(";;-------------- -------- ---------- ----------- ---------- ---------------------------- -------- -------- -------- -------- --------")
        content.append(f"{ww['id']:<16} {ww['invert']:<8.2f} {ww['max_depth']:<10.2f} {ww['init_depth']:<10.2f} {'FUNCTIONAL':<10} {ww['area']:<8.2f} 0 0 0 {0.0:<8.2f} {0.0:<8.2f} {0.0:<8.2f} {0.0:<8.2f}")
        content.append("")
        
        # Conduits section
        content.append("[CONDUITS]")
        content.append(";;Name           From Node        To Node          Length     Roughness  InOffset   OutOffset  InitFlow   MaxFlow   ")
        content.append(";;-------------- ---------------- ---------------- ---------- ---------- ---------- ---------- ---------- ----------")
        
        fm = config['force_main']
        content.append(f"{fm['id']:<16} {fm['from']:<16} {fm['to']:<16} {fm['length']:<10.2f} {fm['roughness']:<10.4f} {0.0:<10.2f} {0.0:<10.2f} {0.0:<10.2f} {0.0:<10.2f}")
        
        # Add gravity conduit from discharge node to outfall
        content.append(f"{'GRAVITY1':<16} {dn['id']:<16} {'OUTFALL1':<16} {100.0:<10.2f} {0.013:<10.4f} {0.0:<10.2f} {0.0:<10.2f} {0.0:<10.2f} {0.0:<10.2f}")
        content.append("")
        
        # Pumps section
        content.append("[PUMPS]")
        content.append(";;Name           From Node        To Node          Pump Curve       Status   Sartup Shutoff ")
        content.append(";;-------------- ---------------- ---------------- ---------------- ------ -------- --------")
        
        pump = config['pump']
        content.append(f"{pump['id']:<16} {pump['from']:<16} {pump['to']:<16} {pump['curve']:<16} {'ON':<6} {pump['startup']:<8.2f} {pump['shutoff']:<8.2f}")
        content.append("")
        
        # XSections section
        content.append("[XSECTIONS]")
        content.append(";;Link           Shape        Geom1            Geom2      Geom3      Geom4      Barrels    Culvert   ")
        content.append(";;-------------- ------------ ---------------- ---------- ---------- ---------- ---------- ----------")
        
        # Force main cross-section
        content.append(f"{fm['id']:<16} {'FORCE_MAIN':<12} {fm['diameter']:<16.3f} {0:<10.3f} {0:<10.3f} {0:<10.3f} {1:<10} {0:<10}")
        
        # Gravity conduit cross-section
        gravity_diameter = max(0.2, fm['diameter'] * 1.5)  # Size appropriately
        content.append(f"{'GRAVITY1':<16} {'CIRCULAR':<12} {gravity_diameter:<16.3f} {0:<10.3f} {0:<10.3f} {0:<10.3f} {1:<10} {0:<10}")
        content.append("")
        
        # Curves section
        content.append("[CURVES]")
        content.append(";;Name           Type       X-Value    Y-Value   ")
        content.append(";;-------------- ---------- ---------- ----------")
        
        for flow, head in pump['curve_data']:
            content.append(f"{pump['curve']:<16} {'PUMP4':<10} {flow:<10.4f} {head:<10.2f}")
        content.append("")
        
        # Controls section for pump operation
        content.append("[CONTROLS]")
        content.append(f"RULE R1")
        content.append(f"IF NODE {ww['id']} DEPTH > {pump['startup']}")
        content.append(f"THEN PUMP {pump['id']} STATUS = ON")
        content.append("")
        content.append(f"RULE R2")
        content.append(f"IF NODE {ww['id']} DEPTH < {pump['shutoff']}")
        content.append(f"THEN PUMP {pump['id']} STATUS = OFF")
        content.append("")
        
        # Report section
        content.extend(self.create_report_section())
        
        # Files section
        content.append("[FILES]")
        content.append(";;Interfacing Files")
        content.append("USE HOTSTART \"\"")
        content.append("SAVE HOTSTART \"\"")
        content.append("")
        
        return "\n".join(content)
    
    def create_multiple_pump_system(self, config):
        """
        Create system with multiple pumps in parallel
        
        config = {
            'project_title': str,
            'wet_well': {...},
            'pumps': [
                {'id': str, 'curve': str, 'startup': float, 'shutoff': float, 'curve_data': [...]},
                ...
            ],
            'force_mains': [
                {'id': str, 'diameter': float, 'length': float, 'roughness': float},
                ...
            ],
            'discharge_node': {...}
        }
        """
        # Implementation for multiple pump systems
        # This would extend the single pump system to handle multiple pumps
        pass
    
    def create_network_system(self, nodes, links, pumps):
        """
        Create complex network system from node/link data
        
        Parameters:
        nodes: Dictionary of node configurations
        links: Dictionary of link configurations  
        pumps: Dictionary of pump configurations
        """
        content = []
        
        # Header
        content.extend(self.create_header_sections("Force Main Network"))
        
        # Process nodes
        junctions = []
        storage_nodes = []
        outfalls = []
        
        for node_id, node in nodes.items():
            if node['type'] == 'junction':
                junctions.append(node_id)
            elif node['type'] == 'wet_well':
                storage_nodes.append(node_id)
            elif node['type'] == 'outfall':
                outfalls.append(node_id)
        
        # Junctions section
        if junctions:
            content.append("[JUNCTIONS]")
            content.append(";;Name           Elevation  MaxDepth   InitDepth  SurDepth   Aponded   ")
            content.append(";;-------------- ---------- ---------- ---------- ---------- ----------")
            
            for node_id in junctions:
                node = nodes[node_id]
                content.append(f"{node_id:<16} {node['invert']:<10.2f} {node.get('max_depth', 2.0):<10.2f} {0.0:<10.2f} {node.get('surcharge_depth', 0.0):<10.2f} {0.0:<10.2f}")
            content.append("")
        
        # Storage section
        if storage_nodes:
            content.append("[STORAGE]")
            content.append(";;Name           Elev.    MaxDepth   InitDepth  Shape      Curve Name/Params            N/A      Fevap    Psi      Ksat     IMD     ")
            content.append(";;-------------- -------- ---------- ----------- ---------- ---------------------------- -------- -------- -------- -------- --------")
            
            for node_id in storage_nodes:
                node = nodes[node_id]
                content.append(f"{node_id:<16} {node['invert']:<8.2f} {node['max_depth']:<10.2f} {node.get('init_depth', 1.0):<10.2f} {'FUNCTIONAL':<10} {node.get('area', 50.0):<8.2f} 0 0 0 {0.0:<8.2f} {0.0:<8.2f} {0.0:<8.2f} {0.0:<8.2f}")
            content.append("")
        
        # Outfalls section
        if outfalls:
            content.append("[OUTFALLS]")
            content.append(";;Name           Elevation  Type       Stage Data       Gated    Route To        ")
            content.append(";;-------------- ---------- ---------- ---------------- -------- ----------------")
            
            for node_id in outfalls:
                node = nodes[node_id]
                content.append(f"{node_id:<16} {node['invert']:<10.2f} {'FREE':<10} {'':<16} {'NO':<8} {'':<16}")
            content.append("")
        
        # Conduits section
        content.append("[CONDUITS]")
        content.append(";;Name           From Node        To Node          Length     Roughness  InOffset   OutOffset  InitFlow   MaxFlow   ")
        content.append(";;-------------- ---------------- ---------------- ---------- ---------- ---------- ---------- ---------- ----------")
        
        for link_id, link in links.items():
            if link['type'] == 'force_main':
                content.append(f"{link_id:<16} {link['from']:<16} {link['to']:<16} {link['length']:<10.2f} {link['roughness']:<10.4f} {0.0:<10.2f} {0.0:<10.2f} {0.0:<10.2f} {0.0:<10.2f}")
        content.append("")
        
        # Pumps section
        if pumps:
            content.append("[PUMPS]")
            content.append(";;Name           From Node        To Node          Pump Curve       Status   Sartup Shutoff ")
            content.append(";;-------------- ---------------- ---------------- ---------------- ------ -------- --------")
            
            for pump_id, pump in pumps.items():
                content.append(f"{pump_id:<16} {pump['from']:<16} {pump['to']:<16} {pump['curve']:<16} {'ON':<6} {pump.get('startup', 2.0):<8.2f} {pump.get('shutoff', 0.5):<8.2f}")
            content.append("")
        
        # Cross-sections
        content.append("[XSECTIONS]")
        content.append(";;Link           Shape        Geom1            Geom2      Geom3      Geom4      Barrels    Culvert   ")
        content.append(";;-------------- ------------ ---------------- ---------- ---------- ---------- ---------- ----------")
        
        for link_id, link in links.items():
            if link['type'] == 'force_main':
                content.append(f"{link_id:<16} {'FORCE_MAIN':<12} {link['diameter']:<16.3f} {0:<10.3f} {0:<10.3f} {0:<10.3f} {1:<10} {0:<10}")
        content.append("")
        
        # Pump curves
        if pumps:
            content.append("[CURVES]")
            content.append(";;Name           Type       X-Value    Y-Value   ")
            content.append(";;-------------- ---------- ---------- ----------")
            
            for pump_id, pump in pumps.items():
                if 'curve_data' in pump:
                    for flow, head in pump['curve_data']:
                        content.append(f"{pump['curve']:<16} {'PUMP4':<10} {flow:<10.4f} {head:<10.2f}")
            content.append("")
        
        # Report section
        content.extend(self.create_report_section())
        
        return "\n".join(content)
    
    def validate_input_file(self, inp_content):
        """
        Validate SWMM input file for common errors
        
        Returns:
        dict: Validation results
        """
        lines = inp_content.split('\n')
        errors = []
        warnings = []
        
        # Check for required sections
        required_sections = ['[TITLE]', '[OPTIONS]', '[TIMES]']
        found_sections = []
        
        for line in lines:
            line = line.strip()
            if line.startswith('[') and line.endswith(']'):
                found_sections.append(line)
        
        for section in required_sections:
            if section not in found_sections:
                errors.append(f"Missing required section: {section}")
        
        # Check for nodes and links
        has_nodes = any('[JUNCTIONS]' in s or '[STORAGE]' in s or '[OUTFALLS]' in s for s in found_sections)
        has_links = any('[CONDUITS]' in s or '[PUMPS]' in s for s in found_sections)
        
        if not has_nodes:
            errors.append("No nodes defined in model")
        if not has_links:
            warnings.append("No links defined in model")
        
        # Check for cross-sections if conduits exist
        if '[CONDUITS]' in found_sections and '[XSECTIONS]' not in found_sections:
            errors.append("Conduits defined but no cross-sections provided")
        
        return {
            'errors': errors,
            'warnings': warnings,
            'is_valid': len(errors) == 0,
            'sections_found': found_sections
        }
